### ISSUE TITLE
Is it possible to look for larger primes than uint64_t which is 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by skoroneos** [hickford/primesieve-python#19]
Greetings
Since the inputs to the C++ are defined as uint64 the larger prime number we can look is the maximum value possible for an unsigned long.
Above that we get an error
primes(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "primesieve\_primesieve.pyx", line 5, in primesieve._primesieve.primes (primesieve/_primesieve.cpp:1377)
OverflowError: long int too large to convert
>>> primes(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "primesieve\_primesieve.pyx", line 5, in primesieve._primesieve.primes (primesieve/_primesieve.cpp:1377)
OverflowError: long int too large to convert

Is it possible to extend this to a larger max ? i.e 256bit

**Comment by kimwalisch** [comment]
Sorry, but that is not possible. The primesieve C++ library only supports primes up to 2^64 and  its algorithms are not suited for larger primes.

If you require primes larger than 2^64 you have to look for another library.
